# Generated by Django 5.0.1 on 2025-10-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('institution', models.CharField(max_length=200, verbose_name='Instituição')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Formação',
                'verbose_name_plural': 'Formações',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cargo')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa')),
                ('company_url', models.URLField(blank=True, verbose_name='URL da Empresa')),
                ('period', models.CharField(max_length=100, verbose_name='Período')),
                ('location', models.CharField(max_length=200, verbose_name='Localização')),
                ('company_description', models.TextField(verbose_name='Descrição da Empresa')),
                ('description', models.TextField(verbose_name='Descrição do Cargo')),
                ('responsibilities', models.JSONField(default=list, verbose_name='Responsabilidades')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('location', models.CharField(max_length=200, verbose_name='Localização')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Foto')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Informação Pessoal',
                'verbose_name_plural': 'Informações Pessoais',
            },
        ),
        migrations.CreateModel(
            name='PersonalInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Interesse Pessoal',
                'verbose_name_plural': 'Interesses Pessoais',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Objetivo Profissional',
                'verbose_name_plural': 'Objetivos Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('tech', models.CharField(max_length=200, verbose_name='Tecnologias')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('highlight', models.BooleanField(default=False, verbose_name='Projeto de Destaque')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ai', 'Inteligência Artificial & Machine Learning'), ('programming', 'Linguagens de Programação'), ('frameworks', 'Frameworks & Tecnologias'), ('systems', 'Sistemas Empresariais'), ('management', 'Gestão & Liderança'), ('tools', 'Ferramentas & Plataformas')], max_length=50, verbose_name='Categoria')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('highlight', models.BooleanField(default=False, verbose_name='Destaque')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.TextField(verbose_name='Resumo Principal')),
                ('secondary', models.TextField(verbose_name='Resumo Secundário')),
                ('ai_specialization', models.TextField(verbose_name='Especialização em IA')),
            ],
            options={
                'verbose_name': 'Resumo',
                'verbose_name_plural': 'Resumos',
            },
        ),
    ]
